# Cypress in GitHub Codespaces https://devopstar.com/2022/01/03/cypress-testing-in-devcontainers-and-github-codespaces/
version: '3'

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      DISPLAY: ":14"
      LIBGL_ALWAYS_INDIRECT: 0
    volumes_from:
      - x11-bridge:rw
    depends_on:
      - x11-bridge

  x11-bridge: # https://github.com/JAremko/docker-x11-bridge
    image: jare/x11-bridge
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ports:
      - "8080:8080"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "8080"
      XPRA_PASSWORD: "1234" # This password can be anything you want.