name: E2E tests

on:
  # Configure this workflow to trigger on pull requests and pushes to main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  cypress:
    name: Cypress with Happo
    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
      HAPPO_NONCE: '${{ github.event_name }}-${{ github.sha }}'
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]

    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Run Cypress
        uses: cypress-io/github-action@ffbc3616ae4754115d05d414810ff4a8e48fc6de
        with:
          install: false
          build: npm run build
          start: npm run serve
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
          group: merge
          # tag will be either "push" or "pull_request"
          tag: ${{ github.event_name }}
          command-prefix: npx happo-e2e -- npx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # - if the event is push, the title will be undefined
          # and Cypress will get the commit message from Git information
          # - if the event is pull_request, then we set the commit
          # message to the pull request title
          # https://github.com/cypress-io/github-action/issues/124#issuecomment-653180260
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}

      - name: Finalize Happo
        run: npx happo-e2e finalize
        if: always()
